name: MycoForge
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Update Rustup
        run: rustup update stable
      - name: Check
        run: cargo check --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Generate Code Coverage via tarpaulin
        run: cargo tarpaulin --out Xml
      - name: Coverage report via Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: kpindur/mycoforge
