name: MycoForge
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Update Rustup
        run: rustup update stable
      - name: Check
        run: cargo check --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Cache Tarpaulin dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ./target
          key: tarpaulin-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            tarpaulin-${{ runner.os }}-
      - name: Generate Code Coverage via tarpaulin
        run: |
          if ! command -v cargo-tarpaulin &> /dev/null; then
            cargo install cargo-tarpaulin
          fi
          cargo tarpaulin --out Xml

      - name: Coverage report via Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: kpindur/mycoforge
